import { News } from "@/Modals/allmodals";

export const mockNews: News[] = [
  // Cricket news
  {
    id: 1,
    title: "IPL 2026 Schedule: Full Match List, Dates, Venues & Timings",
    summary: "Complete breakdown of fixtures, venues, and timings for the upcoming IPL season.",
    imageUrl: "https://picsum.photos/seed/ipl/800/400",
    publishedAt: "01 Feb 2026",
    source: "Sports Daily",
    variant: "hero",
    category: "cricket",
  },
  {
    id: 2,
    title: "Smriti Mandhana: The Complete Profile of India’s Cricket Star",
    summary: "A deep dive into Smriti Mandhana’s career, achievements, and future prospects.",
    imageUrl: "https://picsum.photos/seed/smriti/400/250",
    publishedAt: "01 Feb 2026",
    source: "Sports Desk",
    variant: "side",
    category: "cricket",
  },
  {
    id: 3,
    title: "Men’s T20i All-Rounder Rankings 2025",
    summary: "Latest ICC rankings for all-rounders in T20 internationals.",
    imageUrl: "https://picsum.photos/seed/rankings/400/250",
    publishedAt: "10 Jun 2025",
    source: "ICC",
    variant: "side",
    category: "cricket",
  },
  {
    id: 4,
    title: "IPL 2026: Mega Auction Highlights",
    summary: "All the major signings and team changes in IPL 2026 Mega Auction.",
    imageUrl: "https://picsum.photos/seed/guide/400/250",
    publishedAt: "05 Feb 2026",
    source: "Cricbuzz",
    variant: "list",
    category: "cricket",
  },
  {
    id: 5,
    title: "India vs Australia T20 Series Preview",
    summary: "Predictions, squads, and key matchups for the T20 series.",
    imageUrl: "https://picsum.photos/seed/ipl/400/250",
    publishedAt: "28 Mar 2026",
    source: "ICC",
    variant: "side",
    category: "cricket",
  },

  // Football news
  {
    id: 6,
    title: "Football Champions League: Group Stage Recap",
    summary: "Latest updates and match analysis from the group stage of the Champions League.",
    imageUrl: "https://picsum.photos/seed/football1/400/250",
    publishedAt: "18 Mar 2026",
    source: "BBC Sport",
    variant: "hero",
    category: "football",
  },
  {
    id: 7,
    title: "Messi Scores Again in El Clasico",
    summary: "A detailed look at Messi's decisive goal in the latest El Clasico match.",
    imageUrl: "https://picsum.photos/seed/football2/400/250",
    publishedAt: "15 Mar 2026",
    source: "Sky Sports",
    variant: "side",
    category: "football",
  },
  {
    id: 8,
    title: "Premier League 2026: Title Race Analysis",
    summary: "Breaking down the contenders for the Premier League title this season.",
    imageUrl: "https://picsum.photos/seed/football3/400/250",
    publishedAt: "20 Mar 2026",
    source: "The Guardian",
    variant: "list",
    category: "football",
  },
  {
    id: 9,
    title: "UEFA Europa League: Quarter Final Highlights",
    summary: "Best goals and key performances from the Europa League quarter finals.",
    imageUrl: "https://picsum.photos/seed/football1/400/250",
    publishedAt: "21 Mar 2026",
    source: "ESPN",
    variant: "hero",
    category: "football",
  },
  {
    id: 10,
    title: "Champions League Final Preview",
    summary: "Everything to know before the big final match of the season.",
    imageUrl: "https://picsum.photos/seed/football2/400/250",
    publishedAt: "30 Mar 2026",
    source: "BBC Sport",
    variant: "hero",
    category: "football",
  },

  // Chess news
  {
    id: 11,
    title: "Grandmaster Magnus Carlsen Wins Chess Championship",
    summary: "Highlights of the championship and analysis of key matches.",
    imageUrl: "https://picsum.photos/seed/chess1/400/250",
    publishedAt: "10 Jan 2026",
    source: "Chess.com",
    variant: "hero",
    category: "chess",
  },
  {
    id: 12,
    title: "Top 10 Chess Openings for 2026",
    summary: "Strategies and moves that top players are using this year.",
    imageUrl: "https://picsum.photos/seed/chess2/400/250",
    publishedAt: "12 Jan 2026",
    source: "ChessBase",
    variant: "side",
    category: "chess",
  },
  {
    id: 13,
    title: "Young Chess Prodigy Shatters Records",
    summary: "Profile of the youngest grandmaster in the chess world.",
    imageUrl: "https://picsum.photos/seed/chess3/400/250",
    publishedAt: "15 Jan 2026",
    source: "Chess Daily",
    variant: "list",
    category: "chess",
  },
  {
    id: 14,
    title: "How AI is Changing Chess Training",
    summary: "Exploring how AI engines are reshaping professional chess practice.",
    imageUrl: "https://picsum.photos/seed/chess1/400/250",
    publishedAt: "20 Jan 2026",
    source: "Tech Chess",
    variant: "side",
    category: "chess",
  },
  {
    id: 15,
    title: "World Chess Federation Annual Report",
    summary: "Important announcements and updates from FIDE for 2026.",
    imageUrl: "https://picsum.photos/seed/chess2/400/250",
    publishedAt: "25 Jan 2026",
    source: "FIDE",
    variant: "list",
    category: "chess",
  },
];  