import { News } from "@/Modals/allmodals";

export const newsData: News[] = [
  {
    id: 1,
    title: "IPL 2026 Schedule: Full Match List, Dates, Venues & Timings",
    summary: "Complete breakdown of fixtures, venues, and timings for the upcoming IPL season.",
    imageUrl: "https://picsum.photos/seed/ipl/800/400",
    publishedAt: "01 Feb 2026",
    source: "Sports Daily",
    variant: "hero",
  },
  {
    id: 2,
    title: "IPL 2026 Schedule: Full Match List, Dates, Venues & Timings",
    summary: "Complete breakdown of fixtures, venues, and timings for the upcoming IPL season.",
    imageUrl: "https://picsum.photos/seed/ipl/800/400",
    publishedAt: "01 Feb 2026",
    source: "Sports Daily",
    variant: "hero",
  },
  {
    id: 3,
    title: "Smriti Mandhana: The Complete Profile of India’s Cricket Star",
    summary: "A deep dive into Smriti Mandhana’s career, achievements, and future prospects.",
    imageUrl: "https://picsum.photos/seed/smriti/400/250",
    publishedAt: "01 Feb 2026",
    source: "Sports Desk",
    variant: "side",
  },
  {
    id: 4,
    title: "Singapore Grand Prix 2025 Overview",
    summary: "Highlights, race analysis, and unforgettable moments from the Singapore GP.",
    imageUrl: "https://picsum.photos/seed/f1/400/250",
    publishedAt: "18 Feb 2025",
    source: "F1 Insider",
    variant: "side",
  },
  {
    id: 5,
    title: "Men’s T20i All-Rounder Rankings 2025",
    summary: "Latest ICC rankings for all-rounders in T20 internationals.",
    imageUrl: "https://picsum.photos/seed/rankings/400/250",
    publishedAt: "10 Jun 2025",
    source: "ICC",
    variant: "side",
  },
  {
    id: 6,
    title: "IPL 2026: The Ultimate Guide to Dates, Teams, Mega Auction & More",
    summary: "Everything you need to know about IPL 2026 in one place.",
    imageUrl: "https://picsum.photos/seed/guide/400/250",
    publishedAt: "01 Feb 2026",
    source: "Sports Desk",
    variant: "list",
  },
  {
    id: 7,
    title: "Startup Ecosystem Booms in India",
    summary: "New startups are attracting record investments this quarter.",
    imageUrl: "https://picsum.photos/seed/startup/400/250",
    publishedAt: "14 Mar 2026",
    source: "Business Insider",
    variant: "list",
  },
];
